# This is a basic workflow to help you get started with Actions

name: Hello Mundo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  job1:
    name: Primeiro Job
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1
        run: env | sort
  
  job2:
    name: Segundo Job
    runs-on: windows-latest
    steps:
      - name: Passo 1
        run: "Get-ChildItem Env: | Sort-Object Name"
        
  job3:
    name: Terceiro Job
    runs-on: ubuntu-latest
    needs: [job1, job2]
    
    steps:
      - name: Ultimo passo
        run: curl github.com

 
